In [1]:
import time
import threading
from librosa.feature import melspectrogram
import time
import matplotlib.pyplot as plt
import numpy as np
import theano
#from train_network import build_model
import keras


# tools to create the music tagging dataset
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from os.path import isfile

import ast
import glob

import pickle
import json
from pprint import pprint

from shutil import copyfile

import librosa
import librosa.display

from collections import Counter
from sklearn.metrics import classification_report, accuracy_score

from keras import backend as K

from keras.models import Sequential, Model
from keras.layers import Input, Dense, TimeDistributed, LSTM, Dropout, Activation
from keras.layers import Convolution2D, MaxPooling2D, Flatten, AveragePooling2D, ZeroPadding2D
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import ELU, LeakyReLU
from keras.callbacks import ModelCheckpoint
from keras import backend
from keras import metrics
from keras.utils import np_utils
from keras.optimizers import Adam
from keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint

from sklearn.preprocessing import normalize
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import hamming_loss, coverage_error, label_ranking_average_precision_score, label_ranking_loss
from keras import optimizers
from timeit import default_timer as timer

from time import sleep
from numpy import array, random, arange, float32, float64, zeros
import matplotlib.pyplot as plt
import sounddevice as sd

%matplotlib inline
%load_ext autoreload

%autoreload


Using TensorFlow backend.


In [2]:
from utils import *


In [4]:
output_on_osc_route = '/lx/output/enabled'

In [20]:
client = udp_client.SimpleUDPClient("0.0.0.0", 3030)

def send_osc(route, message):
    client.send_message(route, message)

In [9]:
client()

TypeError: 'SimpleUDPClient' object is not callable

In [21]:
send_osc(output_on_osc_route, 1)


In [3]:
librosa.__version__

'0.5.1'

In [3]:
######################################################################
#                      GET data FROM LOGGER
######################################################################


#data_file = "/Users/aaronopp/Desktop/logger/data/out.txt"
TRAINING_DATA_PATH = '/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/'
data_file =  TRAINING_DATA_PATH + 'logger_training_output_raw_17_21.txt'
%pwd

'/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ'

In [4]:
X_test = np.load(TRAINING_DATA_PATH + 'x_train_raw_17_21.npy')
time_test_scaled = np.load(TRAINING_DATA_PATH + 'time_test_scaled_raw_17_21.npy')



FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/x_train_raw_17_21.npy'

In [6]:
%pwd

'/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ'

In [8]:
%cd training_data

/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data


In [9]:
%ls

aaron_test/   aaronopp/     augmentation/ notebooks/    test/


In [11]:
%cd aaronopp

/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaronopp


In [12]:
%ls

2_2/  3_27/


In [13]:
%cd 2_2

/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaronopp/2_2


In [17]:
%cd ../aaron_test

[Errno 2] No such file or directory: '../aaron_test'
/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaronopp/2_2


In [24]:
%cd 3_28
%ls
%pwd

/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaron_test/3_28
logger_training_output_raw_12_5.txt  x_train_raw_12_5.npy
time_test_scaled_raw_12_5.npy


'/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaron_test/3_28'

In [11]:
X_test_2_7 = np.load('/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaronopp/2_2/x_train_raw_14_37.npy')
X_test_2_7_2 = np.load('/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaronopp/2_2/x_train_raw_13_26.npy')

In [15]:
X_test_3_6 = np.load(TRAINING_DATA_PATH + 'aaron_test/3_28/x_train_raw_12_5.npy')

In [37]:
X_test_2_7.shape

(33, 1, 96, 938)

In [38]:
X_test_3_6.shape

(21, 1, 96, 938)

In [58]:
X_test_2_7

array([[[[-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         ..., 
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.]]],


       [[[-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         ..., 
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.]]],


       [[[-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         ..., 
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -1

In [16]:
X_test_3_6

array([[[[-75.42039942, -75.42039942, -75.42039942, ..., -25.38849157,
          -26.9045172 , -10.32668278],
         [-75.42039942, -75.42039942, -75.42039942, ..., -24.57257242,
          -32.21769394,  -9.09937285],
         [-75.42039942, -75.42039942, -75.42039942, ...,  -5.70023973,
           -4.29009399,  -2.07229619],
         ..., 
         [-75.42039942, -75.42039942, -75.42039942, ..., -59.83688765,
          -48.2293203 , -55.09807552],
         [-75.42039942, -75.42039942, -75.42039942, ..., -57.70575838,
          -52.27539831, -56.71591362],
         [-75.42039942, -75.42039942, -75.42039942, ..., -64.54942004,
          -60.26246387, -58.64780082]]],


       [[[-75.39318847, -75.39318847, -75.39318847, ...,  -3.15952009,
           -6.55243659,  -8.37427942],
         [-75.39318847, -75.39318847, -75.39318847, ...,  -4.86916233,
           -3.20341427,  -1.42474439],
         [-75.39318847, -75.39318847, -75.39318847, ...,  -4.85402585,
            1.60399024,  -1.10

In [19]:
X_test_2_7_2[8]

array([[[-24.54279771, -22.27110123, -24.65715374, ..., -15.21988993,
         -15.14935913, -15.99845973],
        [-10.46248696, -10.14248315, -10.69857107, ..., -10.90318379,
         -10.61214501, -11.01277526],
        [ -9.69846653, -11.05639407, -10.11547591, ..., -11.7998276 ,
         -10.37465681,  -8.98439641],
        ..., 
        [-59.60804586, -65.35120583, -61.90446099, ..., -50.93240778,
         -48.70150722, -58.15531141],
        [-63.05692323, -63.57081484, -67.13552674, ..., -59.22721776,
         -59.33560134, -58.21658529],
        [-69.28882028, -70.754038  , -71.74159488, ..., -67.55567217,
         -66.01885621, -65.38959933]]])

In [20]:
X_test_3_6[7]

array([[[-25.2597602 , -12.40139435,  -6.26085025, ...,  -3.20881777,
          -4.97709118,  -3.7991964 ],
        [ -3.9453714 ,  -5.18372374,   0.99227724, ...,  -5.19928083,
         -12.66235949,  -5.76759912],
        [ -3.66390231,  -4.1991667 ,  -2.60069296, ..., -13.4182018 ,
         -16.17427178, -14.07109729],
        ..., 
        [-74.05700375, -74.5969288 , -75.35907811, ..., -75.35907811,
         -75.35907811, -75.35907811],
        [-75.35907811, -75.35907811, -75.35907811, ..., -75.35907811,
         -75.35907811, -75.35907811],
        [-75.35907811, -75.35907811, -75.35907811, ..., -75.35907811,
         -75.35907811, -75.35907811]]])

In [44]:
######################################################################
#                      GET data FROM LOGGER
######################################################################


#data_file = "/Users/aaronopp/Desktop/logger/data/out.txt"
TRAINING_DATA_PATH = '/Users/aaronopp/Desktop/SymmetryLabs/winter_sun/SLStudio/AI_VJ/training_data/aaronopp/1_11/'
data_file =  TRAINING_DATA_PATH + 'logger_training_output_raw_17_21.txt'
%pwd

'/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/training_data/aaron_test/3_28'

In [4]:
TRAINING_DATA_PATH = '/Users/aaronopp/Desktop/AI_VJ_2to3/py2/x_train_raw_16_31.npy'

In [5]:
x_test_py2 = np.load('/Users/aaronopp/Desktop/AI_VJ_2to3/py2/x_train_raw_16_31.npy')
x_test_py3 = np.load('/Users/aaronopp/Desktop/AI_VJ_2to3/py3/x_train_raw_16_23.npy')




In [45]:
X_test = np.load(TRAINING_DATA_PATH + 'x_train_raw_17_21.npy')
time_test_scaled = np.load(TRAINING_DATA_PATH + 'time_test_scaled_raw_17_21.npy')



FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaronopp/Desktop/SymmetryLabs/winter_sun/SLStudio/AI_VJ/training_data/aaronopp/1_11/x_train_raw_17_21.npy'

In [48]:
x_1 = np.load('/Users/aaronopp/Desktop/AI_VJ/training_data/1_9/x_train_raw_19_7.npy')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaronopp/Desktop/AI_VJ/training_data/1_9/x_train_raw_19_7.npy'

In [25]:
x_test_py2[0].mean(axis=2)

array([[-33.91684092, -42.31735014, -42.78375883, -39.31186533,
        -37.35366963, -33.87101908, -27.19040918, -25.37650783,
        -27.64165183, -31.27300271, -28.56400819, -27.82580786,
        -28.59638275, -29.03036428, -32.76541579, -35.07095868,
        -28.66721562, -26.28641317, -31.08466897, -34.12852261,
        -35.79649133, -39.4105006 , -38.03346607, -38.0905592 ,
        -42.63487012, -40.41532357, -38.05510217, -37.99715984,
        -40.73249698, -45.10057139, -46.2458873 , -46.030269  ,
        -50.52663494, -52.73873361, -47.04475001, -45.93743687,
        -52.89394434, -53.62224759, -49.28255665, -48.67223477,
        -49.90805921, -51.75647011, -57.80235685, -54.69817854,
        -52.80772531, -55.34569262, -57.14647729, -55.55663344,
        -56.34538084, -58.56140406, -57.43299042, -57.63721336,
        -58.59511432, -58.94677436, -64.24839458, -66.50670691,
        -57.52502546, -59.25424588, -69.97770756, -70.19879169,
        -66.25259746, -66.01221785, -65.

In [18]:
for i in range(0, 8):
    
    print('python 2 mean:' , x_test_py2[i].mean())
    print('max:' , x_test_py2[i].max())
    print('min:' , x_test_py2[i].min())
    print('std:', x_test_py2[i].std())
    print('var:', x_test_py2[i].var())
    print('python 3 mean:', x_test_py3[i].mean())
    print('max:' , x_test_py3[i].max())
    print('min:' , x_test_py3[i].min())
    print('std:', x_test_py3[i].std())
    print('var:', x_test_py3[i].var())

python 2 mean: -57.1618891377
max: -1.41543763123
min: -81.4154376312
std: 20.5846946683
var: 423.729654586
python 3 mean: -57.2274499807
max: -1.38757582455
min: -81.3875758245
std: 20.5833089562
var: 423.672607586
python 2 mean: -55.6374131266
max: -3.10673349066
min: -83.1067334907
std: 21.4996163896
var: 462.233504899
python 3 mean: -55.5278668733
max: -1.46913914623
min: -81.4691391462
std: 20.96292939
var: 439.444408611
python 2 mean: -51.1587414718
max: 2.18599636746
min: -77.8140036325
std: 20.562962413
var: 422.835423198
python 3 mean: -53.0326997163
max: -1.62767637791
min: -81.6276763779
std: 21.5764134306
var: 465.54161653
python 2 mean: -46.393920441
max: 2.75654850671
min: -77.2434514933
std: 20.0483407872
var: 401.935968321
python 3 mean: -46.5690621999
max: 3.29287845756
min: -76.7071215424
std: 20.0498521665
var: 401.996571898
python 2 mean: -48.9456518571
max: 3.29421210146
min: -76.7057878985
std: 20.0967850201
var: 403.880768144
python 3 mean: -48.458780048
max: 2.5

In [5]:
x_full = np.load('/Users/aaronopp/Desktop/SymmetryLabs/ML_model/training_data/X_train_full.npy')

In [53]:
x_1

array([[[[-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         ..., 
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.]]],


       [[[-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         ..., 
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.]]],


       [[[-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -100., -100., ..., -100., -100., -100.],
         ..., 
         [-100., -100., -100., ..., -100., -100., -100.],
         [-100., -1

In [69]:
def graph_MS(data, line):
    if data.ndim == 4:
        S = data[line].reshape(data[line].shape[1:])
    if data.ndim == 3:
        S = data[line].reshape(data[line].shape[0:])
    else:
        S = data
    print(S.shape)
    print(S)
    plt.figure(figsize=(10, 4))
    librosa.display.specshow(librosa.power_to_db(S,
                                              ref=np.max),
                       sr=16000, hop_length=256,  y_axis='mel', fmax=8000,
                          x_axis='time')
    plt.colorbar(format='%+2.0f dB')
    plt.title('Mel spectrogram')
    plt.tight_layout()
def graph_MS_test(data, line):
    if data.ndim == 4:
        S = data[line].reshape(data[line].shape[1:])
    if data.ndim == 3:
        S = data[line].reshape(data[line].shape[0:])
    else:
        S = data
    print(S.shape)
    print(S)
    plt.figure(figsize=(10, 4))
    librosa.display.specshow(librosa.power_to_db(S,
                                              ref=np.max),
                       sr=16000, hop_length=256,  y_axis='mel', fmax=8000,
                          x_axis='time')
    plt.colorbar(format='%+2.0f dB')
    plt.title('Mel spectrogram')
    plt.tight_layout()
    return S

In [86]:
s1 = librosa.power_to_db(S**2, ref=np.max)

In [31]:
t1 = np.zeros((1, 1, 96, 938))

In [33]:
t1[0, :] = x_full[0]

In [35]:
t1.shape

(1, 1, 96, 938)

In [27]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [22]:
# load in model to check predictions.. .. . .
X_train_shape = np.array((1765, 1, 96, 938))
Y_pattern_train_shape = np.array((1765, 1, 96, 938))
Y_pattern_classes = 24

model_pattern = build_model_linear_end_pattern(X_train_shape, Y_pattern_train_shape, nb_classes = Y_pattern_classes)


('ALL THE SHAPES', array([1765,    1,   96,  938]), array([1765,    1,   96,  938]), 24)


In [53]:
for i in range(0, 10):
    t1 = np.zeros((1, 1, 96, 938))
    t1[0, :] = x_full[-i]
    Spec = t1
    Spec_small = Spec[:, :, :, -313:]

    print('range number:'+ str(i))
    speed_predict = model_speed.predict(Spec)
    color_predict = model_color.predict(Spec)
    pattern_predict = model_pattern.predict(Spec)
    print('pattern predict shape!', pattern_predict.shape)
    blur_predict = model_blur.predict(Spec_small)
    desat_predict = model_desat.predict(Spec_small)

    #print 'max data pos: ' , speed_predict.argmax()
    speed_label, speed_index = get_max_label(speed_predict, speed_labels)
    color_label, color_index = get_max_label(color_predict, color_labels_encoding)
    pattern_label, pattern_index = get_max_label(pattern_predict, patterns_full)

    blur_label, blur_index = get_max_label(blur_predict, effect_labels_full)  
    desat_label, desat_index = get_max_label(desat_predict, effect_labels_full)  

    print('speed: ', speed_label)
    print('color: ', color_label)
    print('pattern: ', pattern_label)
    print('blur: ', blur_label)
    print('desat: ', desat_label)
    print('PATTERN MAX READING: ', pattern_predict.max())
    

range number:0
pattern predict shape! (1, 23)
max data pos:  1
max data pos:  5
max data pos:  12
max data pos:  0
max data pos:  0
speed:  medium
color:  blue
pattern:  Rings
blur:  None
desat:  None
PATTERN MAX READING:  0.717677
range number:1
pattern predict shape! (1, 23)
max data pos:  1
max data pos:  7
max data pos:  13
max data pos:  0
max data pos:  0
speed:  medium
color:  magenta
pattern:  ShiftingPlane
blur:  None
desat:  None
PATTERN MAX READING:  0.777754
range number:2
pattern predict shape! (1, 23)
max data pos:  1
max data pos:  7
max data pos:  13
max data pos:  0
max data pos:  0
speed:  medium
color:  magenta
pattern:  ShiftingPlane
blur:  None
desat:  None
PATTERN MAX READING:  0.903745
range number:3
pattern predict shape! (1, 23)
max data pos:  1
max data pos:  7
max data pos:  13
max data pos:  0
max data pos:  0
speed:  medium
color:  magenta
pattern:  ShiftingPlane
blur:  None
desat:  None
PATTERN MAX READING:  0.875195
range number:4
pattern predict shape! (

In [47]:
X_train_shape = np.array((1765, 1, 96, 938))

Y_pattern_train_shape = np.array((1765, 1, 96, 938))
Y_color_train_shape = np.array((1765, 1, 96, 938)) #np.load(DATA_FOLDER + 'Y_color_train_v2.npy')
Y_speed_train_shape = np.array((1765, 1, 96, 938)) #np.load(DATA_FOLDER + 'Y_speed_train_v2.npy')

X_train_small_shape = np.array((856, 1, 96, 313)) #np.load(DATA_FOLDER + 'X_train_small_v2.npy')
Y_blur_train_shape = np.array((856, 1, 96, 313)) #np.load(DATA_FOLDER + 'Y_blur_v2.npy')
Y_desat_train_shape = np.array((856, 1, 96, 313)) #np.load(DATA_FOLDER + 'Y_desat_v2.npy')

Y_speed_classes = 3
Y_color_classes = 8
Y_pattern_classes = 24
Y_effect_classes = 4

print('checking shapes')
print('pattern shape: ', Y_pattern_train_shape)
print('color shape: ', Y_color_train_shape)
print('speed shape: ', Y_speed_train_shape)

print('comparing all lengths!')
print('x test trimmed shape: ', X_train_shape)

print('x test trimmed shape: ', X_train_small_shape)
#print 'Y_param shape: ', Y_param_full.shape
print('Y_blur shape: ', Y_blur_train_shape)
print('Y_desat shape: ', Y_desat_train_shape)

############################
# build and load models
############################

# big models, 15 sec

model_speed = build_model_linear_end(X_train_shape, Y_speed_train_shape, nb_classes= Y_speed_classes)          
model_color = build_model_linear_end(X_train_shape, Y_color_train_shape, nb_classes= Y_color_classes)
model_pattern = build_model_linear_end_pattern(X_train_shape, Y_pattern_train_shape, nb_classes = Y_pattern_classes)

# v2 MODELS
# small models (5sec)

model_blur = build_model_linear_end(X_train_small_shape, Y_blur_train_shape, nb_classes=Y_effect_classes)
model_desat = build_model_linear_end(X_train_small_shape, Y_desat_train_shape, nb_classes=Y_effect_classes)


checking shapes
pattern shape:  [1765    1   96  938]
color shape:  [1765    1   96  938]
speed shape:  [1765    1   96  938]
comparing all lengths!
x test trimmed shape:  [1765    1   96  938]
x test trimmed shape:  [856   1  96 313]
Y_blur shape:  [856   1  96 313]
Y_desat shape:  [856   1  96 313]
('ALL THE SHAPES', array([1765,    1,   96,  938]), array([1765,    1,   96,  938]), 3)
('ALL THE SHAPES', array([1765,    1,   96,  938]), array([1765,    1,   96,  938]), 8)
('ALL THE SHAPES', array([1765,    1,   96,  938]), array([1765,    1,   96,  938]), 24)
('ALL THE SHAPES', array([856,   1,  96, 313]), array([856,   1,  96, 313]), 4)
('ALL THE SHAPES', array([856,   1,  96, 313]), array([856,   1,  96, 313]), 4)


In [48]:
model_speed.load_weights(WEIGHTS_FOLDER + 'weights_speed_11_2_noval_85.hdf5')
model_color.load_weights(WEIGHTS_FOLDER + 'weights_color_11_2_noval_91.hdf5')
model_pattern.load_weights(WEIGHTS_FOLDER + 'weights_pattern_11_2_noval_84.hdf5')
model_blur.load_weights(WEIGHTS_FOLDER + 'weights_blur_11_2_noval_84.hdf5')
model_desat.load_weights(WEIGHTS_FOLDER + 'weights_desat_11_2_noval_80.hdf5')

In [43]:
WEIGHTS_FOLDER = '/Users/aaronopp/Desktop/SymmetryLabs/SLStudio/AI_VJ/model_weights/v2/'



In [46]:
pattern_predict = model_pattern.predict(t1)
pattern_label, pattern_index = get_max_label(pattern_predict, patterns_full)

print('pattern: ', pattern_label)


max data pos:  12
pattern:  Rings


In [ ]:
Spec 
Spec_small = Spec[:, :, :, -313:]


In [ ]:
speed_predict = model_speed.predict(Spec)
color_predict = model_color.predict(Spec)
pattern_predict = model_pattern.predict(Spec)
print('pattern predict shape!', pattern_predict.shape)
blur_predict = model_blur.predict(Spec_small)
desat_predict = model_desat.predict(Spec_small)

#print 'max data pos: ' , speed_predict.argmax()
speed_label, speed_index = get_max_label(speed_predict, speed_labels)
color_label, color_index = get_max_label(color_predict, color_labels_encoding)
pattern_label, pattern_index = get_max_label(pattern_predict, patterns_full)

blur_label, blur_index = get_max_label(blur_predict, effect_labels_full)  
desat_label, desat_index = get_max_label(desat_predict, effect_labels_full)  

print('speed: ', speed_label)
print('color: ', color_label)
print('pattern: ', pattern_label)
print('blur: ', blur_label)
print('desat: ', desat_label)
print('PATTERN MAX READING: ', pattern_predict.max())